apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexo-deploy
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: appn
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: appn
    spec:
      containers:
      - name: app-cont
        image: muteto0/nexoimage:IMAGE_NAME
        ports:
        - containerPort: 8080 
---
apiVersion: v1
kind: Service
metadata:
  name: nexo-svc
  labels:
    app: appn
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31000
    protocol: TCP
  selector:
    app: appn
