name: Docker Build and Push
env:
  IMAGE_NAME: ${{ github.sha }}
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2   
    - name: DockerHub Login
      uses: docker/login-action@v1.12.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }} 
    - name: Docker Build
      uses: docker/build-push-action@v2 
      with:
        context: ./app
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/nexoimage:${{ env.IMAGE_NAME }}
    - name: Update application.yaml
      run : | 
        sed "s/%IMAGE_NAME%" application.yaml
      

